version: '3.2'

services:
  telegraf:
    image: telegraf:1.5.3
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      #      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
      #    volumes:
      #  - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    deploy:
      mode: global
      #      placement:
      #  constraints: [node.platform.os == linux]
  influxdb:
    image: influxdb:1.5.4
    networks:
     - proxy
    volumes:
      - /srv/docker/volumes/portainer:/data
    

networks:
  proxy:
    external: true

